const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const S={view:'cams',region:'Todas',q:'',favOnly:false,pos:null,map:null,userMarker:null,markers:{},selected:null,watch:null,install:null};
const F=new Set(JSON.parse(localStorage.getItem('bc-favs')||'[]'));
const REG=['Todas','Norte','Llevant','Ponent','Palma','Migjorn'];
const WC={};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function save(){localStorage.setItem('bc-favs',JSON.stringify([...F]))}
function thumb(c){if(c.mode==='youtube')return`https://i.ytimg.com/vi/${c.video}/hqdefault.jpg`;if(c.mode==='ipcam')return`https://g0.ipcamlive.com/player/snapshot.php?alias=${c.alias}&t=${Math.floor(Date.now()/300000)}`;return''}
function cams(){let q=S.q.toLowerCase().trim();return CAMERAS.filter(c=>(S.region==='Todas'||c.region===S.region)&&(!S.favOnly||F.has(c.key))&&(!q||`${c.name} ${c.region} ${c.provider}`.toLowerCase().includes(q)))}
function drawFilters(){let e=$('#filters');e.innerHTML='';REG.forEach(r=>{let b=document.createElement('button');b.className='chip'+(S.region===r&&!S.favOnly?' on':'');b.textContent=r;b.onclick=()=>{S.region=r;S.favOnly=false;drawFilters();drawCams()};e.appendChild(b)});let f=document.createElement('button');f.className='chip'+(S.favOnly?' on':'');f.textContent='★ Favoritas';f.onclick=()=>{S.favOnly=!S.favOnly;drawFilters();drawCams()};e.appendChild(f)}
function drawCams(){let list=cams(),g=$('#grid');$('#count').textContent=`${list.length} / ${CAMERAS.length}`;g.innerHTML='';list.forEach(c=>{let card=document.createElement('article');card.className='card';let v=document.createElement('div');v.className='visual';let t=thumb(c);if(t){let i=document.createElement('img');i.loading='lazy';i.src=t;i.alt=c.name;i.onerror=()=>{i.remove();v.insertAdjacentHTML('afterbegin',`<div class="ph">🌊<br>${esc(c.name)}</div>`)};v.appendChild(i)}else v.innerHTML=`<div class="ph">🌊<br>${esc(c.name)}</div>`;v.insertAdjacentHTML('beforeend',`<span class="badge live">● DIRECTO</span><span class="badge prov">${esc(c.provider)}</span>`);let p=document.createElement('button');p.className='play';p.onclick=()=>openCam(c);v.appendChild(p);let f=document.createElement('button');f.className='fav'+(F.has(c.key)?' on':'');f.textContent=F.has(c.key)?'★':'☆';f.onclick=e=>{e.stopPropagation();F.has(c.key)?F.delete(c.key):F.add(c.key);save();drawCams()};v.appendChild(f);let info=document.createElement('div');info.className='info';info.innerHTML=`<div class="name">${esc(c.name)}</div><div class="meta"><span>${esc(c.region)}</span><span>✓ directo</span></div>`;card.append(v,info);g.appendChild(card)})}
function camNode(c){if(c.mode==='youtube'||c.mode==='ipcam'){let f=document.createElement('iframe');f.src=c.mode==='youtube'?`https://www.youtube-nocookie.com/embed/${c.video}?autoplay=1&playsinline=1&rel=0`:`https://g0.ipcamlive.com/player/player.php?alias=${c.alias}&autoplay=1`;f.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';f.allowFullscreen=true;return f}if(c.mode==='mjpeg'){let i=document.createElement('img');i.src=c.url;return i}let d=document.createElement('div');d.className='external';d.innerHTML=`<h2>${esc(c.name)}</h2><p>Este proveedor debe abrirse en su página original.</p><a class="btn primary" target="_blank" rel="noopener" href="${esc(c.url)}">Abrir directo ↗</a>`;return d}
function openCam(c){if(!c)return;$('#viewerTitle').textContent=c.name;$('#original').href=c.url;let v=$('#viewer');v.innerHTML='';v.appendChild(camNode(c));$('#viewerModal').classList.add('open')}
function closeCam(){$('#viewerModal').classList.remove('open');$('#viewer').innerHTML=''}
function beach(k){return BEACHES.find(b=>b.key===k)}
function beachCams(b){return b?b.cameraKeys.map(k=>CAMERAS.find(c=>c.key===k)).filter(Boolean):[]}
function openBeachCameras(b){let list=beachCams(b);if(!list.length){$('#sheetTitle').textContent=`${b?.name||'Playa'} · cámaras`;$('#sheetList').innerHTML='<div class="camera-btn"><span>No hay cámaras asociadas.</span></div>';$('#cameraSheet').classList.add('open');return}if(list.length===1){openCam(list[0]);return}$('#sheetTitle').textContent=`${b.name} · cámaras`;let e=$('#sheetList');e.innerHTML='';list.forEach(c=>{let x=document.createElement('button');x.className='camera-btn';x.innerHTML=`<span><strong>${esc(c.name)}</strong><br><small>${esc(c.provider)}</small></span><span>Ver ▶</span>`;x.onclick=()=>{$('#cameraSheet').classList.remove('open');openCam(c)};e.appendChild(x)});$('#cameraSheet').classList.add('open')}
window.openBeachCameras=k=>{const b=beach(k);if(b)openBeachCameras(b)};
function openPrimaryCamera(b){const c=beachCams(b)[0];if(c)openCam(c);else openBeachCameras(b)}
function maps(b){return`https://www.google.com/maps/dir/?api=1&destination=${b.lat},${b.lng}&travelmode=driving`}
function dist(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,x=r(c-a),y=r(d-b),q=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function nearest(){if(!S.pos)return[];return BEACHES.map(b=>({...b,distance:dist(S.pos.lat,S.pos.lng,b.lat,b.lng)})).sort((a,b)=>a.distance-b.distance)}
function dif(a,b){return((a-b+540)%360)-180}
function toward(speed,from,bearing){let to=(from+180)%360;return Math.max(0,speed*Math.cos(dif(to,bearing)*Math.PI/180))}
function label(c){if(c===0)return['☀️','Soleado'];if([1,2,3].includes(c))return['🌤️','Nubosidad'];if([45,48].includes(c))return['🌫️','Niebla'];if([51,53,55,56,57].includes(c))return['🌦️','Llovizna'];if([61,63,65,66,67,80,81,82].includes(c))return['🌧️','Lluvia'];if([95,96,99].includes(c))return['⛈️','Tormenta'];return['🌤️','Variable']}
async function weather(b){let old=WC[b.key];if(old&&Date.now()-old.t<1200000)return old.d;let w=`https://api.open-meteo.com/v1/forecast?latitude=${b.lat}&longitude=${b.lng}&current=temperature_2m,weather_code,wind_speed_10m,wind_direction_10m&timezone=Europe%2FMadrid`;let m=`https://marine-api.open-meteo.com/v1/marine?latitude=${b.lat}&longitude=${b.lng}&hourly=wave_height&forecast_days=1&timezone=Europe%2FMadrid`;let [wr,mr]=await Promise.allSettled([fetch(w),fetch(m)]),cur={},wave=null;if(wr.status==='fulfilled'&&wr.value.ok){let j=await wr.value.json();cur=j.current||{}}if(mr.status==='fulfilled'&&mr.value.ok){let j=await mr.value.json();if(j.hourly?.time?.length){let now=Date.now(),best=0,delta=Infinity;j.hourly.time.forEach((x,i)=>{let d=Math.abs(new Date(x).getTime()-now);if(d<delta){delta=d;best=i}});wave=j.hourly.wave_height?.[best]??null}}let [icon,text]=label(cur.weather_code);let d={icon,text,temp:cur.temperature_2m,onshore:toward(cur.wind_speed_10m||0,cur.wind_direction_10m||0,b.shoreBearing),wave};WC[b.key]={t:Date.now(),d};return d}
function cardHTML(b,w,distance){let temp=w.temp==null?'—':`${Math.round(w.temp)} °C`,wave=w.wave==null?'—':`${Number(w.wave).toFixed(1)} m`;return`${distance!=null?`<div class="distance">${distance.toFixed(1)} km</div>`:''}<div class="metric">${w.icon} <strong>${esc(w.text)}</strong> · ${temp}</div><div class="metric">💨 Hacia la playa: <strong>${Math.round(w.onshore||0)} km/h</strong></div><div class="metric">🌊 Olas: <strong>${wave}</strong></div><div class="actions"><button class="btn primary" onclick="openBeachCameras('${b.key}')">📹 Ver cámaras</button><a class="btn" target="_blank" rel="noopener" href="${maps(b)}">📍 Ir con Google Maps</a></div>`}
async function fillPanel(b,e,distance,title=true){e.innerHTML=`${title?`<h2>${esc(b.name)}</h2>`:''}<p>Cargando datos…</p>`;try{let w=await weather(b);e.innerHTML=`${title?`<h2>${esc(b.name)}</h2>`:''}${cardHTML(b,w,distance)}`}catch{e.innerHTML=`${title?`<h2>${esc(b.name)}</h2>`:''}<p>No se han podido cargar los datos meteorológicos.</p><div class="actions"><button class="btn primary" onclick="openBeachCameras('${b.key}')">📹 Ver cámaras</button><a class="btn" target="_blank" rel="noopener" href="${maps(b)}">📍 Ir con Google Maps</a></div>`}}
function initMap(){if(S.map)return;S.map=L.map('leafletMap').setView([39.65,2.95],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(S.map);BEACHES.forEach(b=>{let m=L.marker([b.lat,b.lng],{title:b.name}).addTo(S.map).bindTooltip(`${b.name} · tocar para ver cámara`);m.on('click',()=>{S.selected=b;let d=S.pos?dist(S.pos.lat,S.pos.lng,b.lat,b.lng):null;fillPanel(b,$('#selected'),d);openPrimaryCamera(b)});S.markers[b.key]=m})}
function selectBeach(b){S.selected=b;S.map?.setView([b.lat,b.lng],13);let d=S.pos?dist(S.pos.lat,S.pos.lng,b.lat,b.lng):null;fillPanel(b,$('#selected'),d)}
async function drawNearest(){let e=$('#nearest');if(!S.pos){e.innerHTML='<h2>Playa más cercana</h2><p>Activa el GPS para calcularla.</p>';return}let n=nearest()[0];e.innerHTML=`<h2>Playa más cercana: ${esc(n.name)}</h2><p>Cargando…</p>`;try{let w=await weather(n);e.innerHTML=`<h2>Playa más cercana: ${esc(n.name)}</h2>${cardHTML(n,w,n.distance)}`}catch{e.innerHTML=`<h2>Playa más cercana: ${esc(n.name)}</h2><div class="distance">${n.distance.toFixed(1)} km</div>`}}
async function drawNear(){let e=$('#nearList');if(!S.pos){e.innerHTML='<div class="near-card"><h3>Activa el GPS</h3><p>Necesito tu ubicación para ordenar las playas.</p></div>';return}e.innerHTML='';for(const b of nearest()){let c=document.createElement('article');c.className='near-card';c.innerHTML=`<h3>${esc(b.name)}</h3><p>Cargando…</p>`;e.appendChild(c);try{let w=await weather(b);c.innerHTML=`<h3>${esc(b.name)}</h3>${cardHTML(b,w,b.distance)}`}catch{c.innerHTML=`<h3>${esc(b.name)}</h3><div class="distance">${b.distance.toFixed(1)} km</div>`}}}
function setPos(lat,lng){S.pos={lat,lng};if(S.map){if(!S.userMarker)S.userMarker=L.circleMarker([lat,lng],{radius:8,color:'#50d5ff',fillColor:'#50d5ff',fillOpacity:1}).addTo(S.map).bindTooltip('Tu posición');else S.userMarker.setLatLng([lat,lng])}drawNearest();if(S.view==='near')drawNear();if(S.selected)selectBeach(S.selected)}
function locate(){localStorage.setItem('bc-location-intro','1');if(!navigator.geolocation)return alert('Este dispositivo no admite geolocalización.');if(S.watch!=null)navigator.geolocation.clearWatch(S.watch);S.watch=navigator.geolocation.watchPosition(p=>{setPos(p.coords.latitude,p.coords.longitude);if(S.map&&!S.centered){S.map.setView([p.coords.latitude,p.coords.longitude],12);S.centered=true}},e=>alert(e.code===1?'Permiso de ubicación denegado.':'No se ha podido obtener tu ubicación.'),{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
function view(v){S.view=v;$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('on',x.id===v));if(v==='map'){initMap();setTimeout(()=>S.map.invalidateSize(),50);drawNearest()}if(v==='near')drawNear()}
$$('.tab').forEach(x=>x.onclick=()=>view(x.dataset.view));$('#search').oninput=e=>{S.q=e.target.value;drawCams()};$('#closeViewer').onclick=closeCam;$('#closeSheet').onclick=()=>$('#cameraSheet').classList.remove('open');$('#locateTop').onclick=locate;$('#locateMap').onclick=locate;$('#locateNear').onclick=locate;$('#mallorca').onclick=()=>{initMap();S.map.setView([39.65,2.95],9)};$('#allowLocation').onclick=()=>{locate();$('#onboarding').classList.remove('show')};$('#later').onclick=()=>{localStorage.setItem('bc-location-intro','1');$('#onboarding').classList.remove('show')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.install=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(S.install){S.install.prompt();await S.install.userChoice;S.install=null;$('#installBtn').hidden=true}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(!localStorage.getItem('bc-location-intro'))$('#onboarding').classList.add('show');drawFilters();drawCams();drawNearest();
