const cfg=window.BEACH_CAM_FIREBASE||{};
const setup=document.querySelector('#setupPanel'),login=document.querySelector('#loginPanel'),master=document.querySelector('#masterPanel'),msg=document.querySelector('#loginMsg'),count=document.querySelector('#deviceCount'),list=document.querySelector('#deviceList');
let map=null,markers={},locations={},aliases={},familyKey='';
function configured(){return !!(cfg.enabled&&cfg.masterEmail&&cfg.firebaseConfig?.apiKey&&cfg.firebaseConfig?.databaseURL)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function age(ts){if(!ts)return'—';let s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return`hace ${s} s`;let m=Math.floor(s/60);if(m<60)return`hace ${m} min`;let h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return`hace ${Math.floor(h/24)} d`}
function google(lat,lng){return`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`}
function ensureMap(){if(map)return;map=L.map('masterMap').setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map)}
function displayName(uid,d){return aliases[uid]||d.label||`Dispositivo ${uid.slice(-4).toUpperCase()}`}
function fitAll(){ensureMap();const pts=Object.values(locations).filter(d=>Number.isFinite(d?.lat)&&Number.isFinite(d?.lng)).map(d=>[d.lat,d.lng]);if(!pts.length){map.setView([20,0],2);return}if(pts.length===1){map.setView(pts[0],10);return}map.fitBounds(L.latLngBounds(pts).pad(.25),{maxZoom:13})}
function renderDevices(){ensureMap();let entries=Object.entries(locations||{}).filter(([,d])=>Number.isFinite(d?.lat)&&Number.isFinite(d?.lng));count.textContent=`${entries.length} dispositivo${entries.length===1?'':'s'}`;list.innerHTML='';let activeIds=new Set();for(const [uid,d] of entries){activeIds.add(uid);const name=displayName(uid,d);let stale=!d.updatedAt||Date.now()-d.updatedAt>5*60*1000;let status=d.online&&!stale?'En línea':'Sin actualizar';let cls=d.online&&!stale?'ok':'warn';let marker=markers[uid];if(!marker){marker=L.marker([d.lat,d.lng],{title:name}).addTo(map);markers[uid]=marker}else marker.setLatLng([d.lat,d.lng]);marker.bindTooltip(`${name} · ${age(d.updatedAt)}`);let card=document.createElement('article');card.className='device';card.innerHTML=`<h3>${esc(name)}</h3><div class="status ${cls}">● ${status}</div><div class="meta">Última posición: ${age(d.updatedAt)}</div><div class="meta">Precisión: ${d.accuracy?Math.round(d.accuracy)+' m':'—'}</div><div class="row"><button class="btn alt" data-center>Ver en mapa</button><a class="btn" target="_blank" rel="noopener" href="${google(d.lat,d.lng)}">Google Maps</a></div><div class="row"><button class="btn alt" data-rename>Renombrar</button><button class="btn alt" data-remove>Eliminar</button></div>`;list.appendChild(card);card.querySelector('[data-center]').onclick=()=>map.setView([d.lat,d.lng],15);card.querySelector('[data-rename]').onclick=async()=>{let n=prompt('Nombre que quieres ver en MASTER:',name);if(n==null)return;n=n.trim().slice(0,40);if(!n)return;await firebase.database().ref(`aliases/${uid}`).set(n)};card.querySelector('[data-remove]').onclick=async()=>{if(!confirm(`¿Eliminar ${name} del MASTER?`))return;await Promise.all([firebase.database().ref(`locations/${uid}`).remove(),firebase.database().ref(`aliases/${uid}`).remove()])}}
  for(const [uid,m] of Object.entries(markers)){if(!activeIds.has(uid)){map.removeLayer(m);delete markers[uid]}}
}
function invitationUrl(){if(!familyKey)return'';return `${location.origin}${location.pathname.replace(/master\.html$/,'install.html')}?join=${encodeURIComponent(familyKey)}`}
function renderInvite(){const url=invitationUrl(),input=document.querySelector('#inviteUrl'),qr=document.querySelector('#inviteQr');if(!url)return;input.value=url;qr.innerHTML='';new QRCode(qr,{text:url,width:190,height:190,correctLevel:QRCode.CorrectLevel.M});document.querySelector('#copyInvite').onclick=async()=>{await navigator.clipboard.writeText(url);document.querySelector('#inviteMsg').textContent='Enlace copiado.'};document.querySelector('#shareInvite').onclick=async()=>{if(navigator.share)await navigator.share({title:'Instalar BEACH CAM',text:'Instala BEACH CAM desde este enlace:',url});else{await navigator.clipboard.writeText(url);document.querySelector('#inviteMsg').textContent='Enlace copiado para enviarlo por WhatsApp.'}}}
async function prepareFamilyKey(){const db=firebase.database(),snap=await db.ref('_private/familyKey').once('value');familyKey=snap.val()||'';if(!familyKey){const fromUrl=new URLSearchParams(location.search).get('setupFamilyKey');familyKey=fromUrl||((crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`).replace(/[^a-zA-Z0-9_-]/g,''));await db.ref('_private/familyKey').set(familyKey)}renderInvite()}
async function loginMaster(){msg.textContent='Entrando…';msg.className='status';try{if(!firebase.apps.length)firebase.initializeApp(cfg.firebaseConfig);let email=document.querySelector('#email').value.trim(),pass=document.querySelector('#password').value;if(email.toLowerCase()!==String(cfg.masterEmail).toLowerCase())throw new Error('Este usuario no está autorizado como MASTER.');await firebase.auth().signInWithEmailAndPassword(email,pass);login.classList.add('hidden');master.classList.remove('hidden');ensureMap();await prepareFamilyKey();firebase.database().ref('locations').on('value',s=>{locations=s.val()||{};renderDevices();fitAll()});firebase.database().ref('aliases').on('value',s=>{aliases=s.val()||{};renderDevices()});document.querySelector('#fitAll').onclick=fitAll;setInterval(renderDevices,60000)}catch(e){msg.textContent=e.message||'No se ha podido iniciar sesión.';msg.className='status err'}}
if(!configured()){setup.classList.remove('hidden')}else{login.classList.remove('hidden');document.querySelector('#email').value=cfg.masterEmail;document.querySelector('#loginBtn').onclick=loginMaster;document.querySelector('#password').addEventListener('keydown',e=>{if(e.key==='Enter')loginMaster()})}
