const cfg=window.BEACH_CAM_FIREBASE||{};
const setup=document.querySelector('#setupPanel'),login=document.querySelector('#loginPanel'),master=document.querySelector('#masterPanel'),msg=document.querySelector('#loginMsg'),count=document.querySelector('#deviceCount'),list=document.querySelector('#deviceList');
let map=null,markers={};
function configured(){return !!(cfg.enabled&&cfg.masterEmail&&cfg.firebaseConfig?.apiKey&&cfg.firebaseConfig?.databaseURL)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function age(ts){if(!ts)return'—';let s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return`hace ${s} s`;let m=Math.floor(s/60);if(m<60)return`hace ${m} min`;let h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return`hace ${Math.floor(h/24)} d`}
function google(lat,lng){return`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`}
function ensureMap(){if(map)return;map=L.map('masterMap').setView([39.65,2.95],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map)}
function renderDevices(data){ensureMap();let entries=Object.entries(data||{}).filter(([,d])=>Number.isFinite(d?.lat)&&Number.isFinite(d?.lng));count.textContent=`${entries.length} dispositivo${entries.length===1?'':'s'}`;list.innerHTML='';let activeIds=new Set();for(const [uid,d] of entries){activeIds.add(uid);let stale=!d.updatedAt||Date.now()-d.updatedAt>5*60*1000;let status=d.online&&!stale?'En línea':'Sin actualizar';let cls=d.online&&!stale?'ok':'warn';let marker=markers[uid];if(!marker){marker=L.marker([d.lat,d.lng],{title:d.label||'Dispositivo'}).addTo(map);markers[uid]=marker}else marker.setLatLng([d.lat,d.lng]);marker.bindTooltip(`${d.label||'Dispositivo'} · ${age(d.updatedAt)}`);let card=document.createElement('article');card.className='device';card.innerHTML=`<h3>${esc(d.label||'Dispositivo')}</h3><div class="status ${cls}">● ${status}</div><div class="meta">Última posición: ${age(d.updatedAt)}</div><div class="meta">Precisión: ${d.accuracy?Math.round(d.accuracy)+' m':'—'}</div><div class="row"><button class="btn alt" data-center="${uid}">Ver en mapa</button><a class="btn" target="_blank" rel="noopener" href="${google(d.lat,d.lng)}">Google Maps</a></div>`;list.appendChild(card);card.querySelector('[data-center]').onclick=()=>map.setView([d.lat,d.lng],15)}for(const [uid,m] of Object.entries(markers)){if(!activeIds.has(uid)){map.removeLayer(m);delete markers[uid]}}if(entries.length){let bounds=L.latLngBounds(entries.map(([,d])=>[d.lat,d.lng]));map.fitBounds(bounds.pad(.25),{maxZoom:13})}}
async function loginMaster(){msg.textContent='Entrando…';msg.className='status';try{if(!firebase.apps.length)firebase.initializeApp(cfg.firebaseConfig);let email=document.querySelector('#email').value.trim(),pass=document.querySelector('#password').value;if(email.toLowerCase()!==String(cfg.masterEmail).toLowerCase())throw new Error('Este usuario no está autorizado como MASTER.');await firebase.auth().signInWithEmailAndPassword(email,pass);login.classList.add('hidden');master.classList.remove('hidden');ensureMap();firebase.database().ref('locations').on('value',snap=>renderDevices(snap.val()||{}),err=>{msg.textContent=err.message;msg.className='status err'});setInterval(()=>firebase.database().ref('locations').once('value').then(s=>renderDevices(s.val()||{})),60000)}catch(e){msg.textContent=e.message||'No se ha podido iniciar sesión.';msg.className='status err'}}
if(!configured()){setup.classList.remove('hidden')}else{login.classList.remove('hidden');document.querySelector('#email').value=cfg.masterEmail;document.querySelector('#loginBtn').onclick=loginMaster;document.querySelector('#password').addEventListener('keydown',e=>{if(e.key==='Enter')loginMaster()})}
