const cfg=window.BEACH_CAM_FIREBASE||{};
const setup=document.querySelector('#setupPanel'),login=document.querySelector('#loginPanel'),master=document.querySelector('#masterPanel'),msg=document.querySelector('#loginMsg'),count=document.querySelector('#deviceCount'),list=document.querySelector('#deviceList'),masterNav=document.querySelector('#masterNav');
let map=null,markers={},locations={},aliases={},familyKey='';
function configured(){return !!(cfg.enabled&&cfg.masterEmail&&cfg.firebaseConfig?.apiKey&&cfg.firebaseConfig?.databaseURL)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function age(ts){if(!ts)return'—';let s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return`hace ${s} s`;let m=Math.floor(s/60);if(m<60)return`hace ${m} min`;let h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return`hace ${Math.floor(h/24)} d`}
function fullTime(ts){if(!ts)return'—';try{return new Date(ts).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'medium'})}catch{return new Date(ts).toLocaleString()}}
function google(lat,lng){return`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`}
function ensureMap(){if(map)return;map=L.map('masterMap').setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map)}
function displayName(uid,d){return aliases[uid]||d.label||`Dispositivo ${uid.slice(-4).toUpperCase()}`}
function pointTime(d){return d.capturedAt||d.updatedAt||0}
function fitAll(){ensureMap();const pts=Object.values(locations).filter(d=>Number.isFinite(d?.lat)&&Number.isFinite(d?.lng)).map(d=>[d.lat,d.lng]);if(!pts.length){map.setView([20,0],2);return}if(pts.length===1){map.setView(pts[0],10);return}map.fitBounds(L.latLngBounds(pts).pad(.25),{maxZoom:13})}
function renderDevices(){ensureMap();let entries=Object.entries(locations||{}).filter(([,d])=>Number.isFinite(d?.lat)&&Number.isFinite(d?.lng));entries.sort((a,b)=>pointTime(b[1])-pointTime(a[1]));count.textContent=`${entries.length} dispositivo${entries.length===1?'':'s'}`;list.innerHTML='';let activeIds=new Set();for(const [uid,d] of entries){activeIds.add(uid);const name=displayName(uid,d),taken=pointTime(d);let stale=!taken||Date.now()-taken>5*60*1000;let status=d.online&&!stale?'Ubicación reciente':'ÚLTIMA UBICACIÓN GUARDADA';let cls=d.online&&!stale?'ok':'warn';let marker=markers[uid];if(!marker){marker=L.marker([d.lat,d.lng],{title:name}).addTo(map);markers[uid]=marker}else marker.setLatLng([d.lat,d.lng]);marker.bindTooltip(`${name} · ${age(taken)}`);let card=document.createElement('article');card.className='device';card.innerHTML=`<h3>${esc(name)}</h3><div class="status ${cls}">● ${status}</div><div class="meta"><strong>Posición tomada:</strong> ${age(taken)} · ${esc(fullTime(taken))}</div><div class="meta"><strong>Recibida por MASTER:</strong> ${age(d.updatedAt)} · ${esc(fullTime(d.updatedAt))}</div><div class="meta"><strong>Precisión GPS:</strong> ${d.accuracy?Math.round(d.accuracy)+' m':'—'}</div><div class="row"><button class="btn" data-center>Ver última ubicación</button><a class="btn" target="_blank" rel="noopener" href="${google(d.lat,d.lng)}">Google Maps</a></div><div class="row"><button class="btn" data-rename>Renombrar</button><button class="btn" data-remove>Eliminar</button></div>`;list.appendChild(card);card.querySelector('[data-center]').onclick=()=>map.setView([d.lat,d.lng],15);card.querySelector('[data-rename]').onclick=async()=>{let n=prompt('Nombre que quieres ver en MASTER:',name);if(n==null)return;n=n.trim().slice(0,40);if(!n)return;await firebase.database().ref(`aliases/${uid}`).set(n)};card.querySelector('[data-remove]').onclick=async()=>{if(!confirm(`¿Eliminar ${name} del MASTER? Este dispositivo quedará bloqueado hasta que se reinstale con un enlace familiar válido.`))return;await Promise.all([firebase.database().ref(`revoked/${uid}`).set(true),firebase.database().ref(`locations/${uid}`).remove(),firebase.database().ref(`aliases/${uid}`).remove()])}}
for(const [uid,m] of Object.entries(markers)){if(!activeIds.has(uid)){map.removeLayer(m);delete markers[uid]}}}
function invitationUrl(){if(!familyKey)return'';return `${location.origin}${location.pathname.replace(/master\.html$/,'install.html')}?join=${encodeURIComponent(familyKey)}`}
function renderInvite(){const url=invitationUrl(),input=document.querySelector('#inviteUrl'),qr=document.querySelector('#inviteQr');if(!url)return;input.value=url;qr.innerHTML='';new QRCode(qr,{text:url,width:210,height:210,correctLevel:QRCode.CorrectLevel.M});document.querySelector('#copyInvite').onclick=async()=>{await navigator.clipboard.writeText(url);document.querySelector('#inviteMsg').textContent='Enlace copiado.'};document.querySelector('#shareInvite').onclick=async()=>{if(navigator.share)await navigator.share({title:'Instalar BEACH CAM',text:'Instala BEACH CAM desde este enlace:',url});else{await navigator.clipboard.writeText(url);document.querySelector('#inviteMsg').textContent='Enlace copiado para enviarlo por WhatsApp.'}};document.querySelector('#downloadQr').onclick=()=>{const canvas=qr.querySelector('canvas'),img=qr.querySelector('img');let href=canvas?.toDataURL('image/png')||img?.src;if(!href)return;let a=document.createElement('a');a.href=href;a.download='BEACH-CAM-QR-FAMILIA.png';a.click()}}
function newKey(){return (crypto.randomUUID?crypto.randomUUID()+crypto.randomUUID():`${Date.now()}-${Math.random()}-${Math.random()}`).replace(/[^a-zA-Z0-9_-]/g,'')}
async function prepareFamilyKey(){const db=firebase.database(),snap=await db.ref('_private/familyKey').once('value');familyKey=snap.val()||'';if(!familyKey){familyKey=newKey();await db.ref('_private/familyKey').set(familyKey)}renderInvite();document.querySelector('#rotateInvite').onclick=async()=>{if(!confirm('¿Crear un enlace familiar nuevo? El anterior dejará de admitir dispositivos nuevos. Los dispositivos ya vinculados seguirán funcionando.'))return;familyKey=newKey();await firebase.database().ref('_private/familyKey').set(familyKey);renderInvite();document.querySelector('#inviteMsg').textContent='Enlace familiar cambiado.'}}
function baseNotice(){return (window.BEACH_CAM_TEXTS&&window.BEACH_CAM_TEXTS.locationNotice)||'BEACH CAM usa tu ubicación para encontrar playas cercanas y compartirla con tu grupo familiar…'}
async function prepareNotice(){const editor=document.querySelector('#locationNoticeEditor'),chars=document.querySelector('#noticeChars'),noticeMsg=document.querySelector('#noticeMsg'),ref=firebase.database().ref('publicConfig/locationNotice');const snap=await ref.once('value');editor.value=(typeof snap.val()==='string'&&snap.val().trim())?snap.val():baseNotice();const updateCount=()=>chars.textContent=editor.value.length;updateCount();editor.oninput=updateCount;document.querySelector('#saveLocationNotice').onclick=async()=>{const text=editor.value.trim();if(!text){noticeMsg.textContent='El texto no puede estar vacío.';noticeMsg.className='status err';return}if(text.length>500){noticeMsg.textContent='Máximo 500 caracteres.';noticeMsg.className='status err';return}await ref.set(text);editor.value=text;updateCount();noticeMsg.textContent='Texto guardado. El QR y el enlace familiar siguen siendo los mismos.';noticeMsg.className='status ok'};document.querySelector('#restoreLocationNotice').onclick=()=>{editor.value=baseNotice();updateCount();noticeMsg.textContent='Texto base cargado. Pulsa Guardar texto para aplicarlo.';noticeMsg.className='status'}}
function setupTabs(){masterNav.classList.remove('hidden');document.querySelector('#headerSub').textContent='Administración privada · mapa familiar';masterNav.querySelectorAll('[data-master-view]').forEach(btn=>btn.onclick=()=>{masterNav.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===btn));document.querySelectorAll('.master-view').forEach(v=>v.classList.remove('on'));document.querySelector(`#master-${btn.dataset.masterView}`).classList.add('on');if(btn.dataset.masterView==='devices'){setTimeout(()=>{map?.invalidateSize();fitAll()},50)}})}
async function loginMaster(){msg.textContent='Entrando…';msg.className='status';try{if(!firebase.apps.length)firebase.initializeApp(cfg.firebaseConfig);let email=document.querySelector('#email').value.trim(),pass=document.querySelector('#password').value;if(email.toLowerCase()!==String(cfg.masterEmail).toLowerCase())throw new Error('Este usuario no está autorizado.');await firebase.auth().signInWithEmailAndPassword(email,pass);login.classList.add('hidden');master.classList.remove('hidden');setupTabs();ensureMap();await Promise.all([prepareFamilyKey(),prepareNotice()]);firebase.database().ref('locations').on('value',s=>{locations=s.val()||{};renderDevices();fitAll()});firebase.database().ref('aliases').on('value',s=>{aliases=s.val()||{};renderDevices()});document.querySelector('#fitAll').onclick=fitAll;document.querySelector('#logoutMaster').onclick=async()=>{await firebase.auth().signOut();location.reload()};setInterval(renderDevices,60000)}catch(e){msg.textContent=e.message||'No se ha podido iniciar sesión.';msg.className='status err'}}
if(!configured()){setup.classList.remove('hidden')}else{login.classList.remove('hidden');document.querySelector('#email').value=cfg.masterEmail;document.querySelector('#loginBtn').onclick=loginMaster;document.querySelector('#password').addEventListener('keydown',e=>{if(e.key==='Enter')loginMaster()})}
