(function(){
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const rows=(window.CAMPER_SPOT_LINES||[]).map(line=>{const x=line.split('|');return{id:x[0],name:x[1],mun:x[2],lat:+x[3],lng:+x[4],type:x[5],price:x[6],night:x[7]==='1',sea:x[8]==='1',status:x[9],note:x[10],source:x[11]}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng));
const PH={
 norte:['https://commons.wikimedia.org/wiki/Special:FilePath/Puerto%20de%20Pollensa.%20Playa.jpg?width=1100','https://commons.wikimedia.org/wiki/Special:FilePath/Far%20de%20l%27Illa%20d%27Alcanada.JPG?width=1100'],
 muro:['https://commons.wikimedia.org/wiki/Special:FilePath/Son%20Serra%20de%20Marina.jpg?width=1100'],
 soller:['https://commons.wikimedia.org/wiki/Special:FilePath/Mallorca%20S%C3%B3ller%20town%20asv2023-04%20img6.jpg?width=1100'],
 trenc:['https://commons.wikimedia.org/wiki/Special:FilePath/Es%20Trenc%2C%20Mallorca%2C%20the%20beach.jpg?width=1100'],
 mondrago:['https://commons.wikimedia.org/wiki/Special:FilePath/Vista%20del%20parque%20natural%20de%20Mondrag%C3%B3.jpg?width=1100'],
 llevant:['https://commons.wikimedia.org/wiki/Special:FilePath/Cala%20Agulla%20Mallorca.jpg?width=1100']
};
let map=null,user=null,userMarker=null,markers=new Map(),filter='all',query='',addMode=false,draftMarker=null;
function dist(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),h=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function route(p){return`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}&travelmode=driving`}
function pointMap(p){return`https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}`}
function iconClass(p){if(p.status==='bad')return'bad';if(p.type==='area'||p.type==='service')return'service';return p.night?'night':'day'}
function statusText(p){if(p.status==='bad')return'⚠️ EVITAR / RESTRICCIÓN';if(p.type==='area')return'🚐 ÁREA CAMPER';if(p.type==='service')return'🚰 SERVICIOS';if(p.night)return'🌙 PERNOCTA REPORTADA';return'🅿️ PARKING / PARADA'}
function typeText(t){return({area:'Área camper',service:'Servicios',parking:'Parking',street:'Calle / estacionamiento',nature:'Paraje / mirador'})[t]||'Punto camper'}
function photos(p){const n=(p.name+' '+p.mun).toLowerCase();if(/alc[uú]dia|alcanada|pollen[cç]a|formentor|vict[oò]ria/.test(n))return PH.norte;if(/muro|picafort|son serra/.test(n))return PH.muro;if(/s[oó]ller|dei[aà]|valldemossa|bunyola|esporles/.test(n))return PH.soller;if(/trenc|r[aà]pita|col[oò]nia de sant jordi|campos|ses salines/.test(n))return PH.trenc;if(/mondrag[oó]|santany[ií]|cala llombards|cal[oó] des moro/.test(n))return PH.mondrago;if(/capdepera|cala agulla|cala gat|mesquida|canyamel|son servera|arta|art[aà]|cala millor|sa coma/.test(n))return PH.llevant;return[]}
function desc(p){if(p.status==='bad')return`Punto conocido por viajeros, pero hay avisos o restricciones que hacen desaconsejable pasar la noche actualmente. Úsalo sobre todo como referencia para no acabar allí por error.`;if(p.type==='area')return`Punto pensado específicamente para autocaravanas o campers. Es una opción más clara cuando quieres dormir con menos incertidumbre y, según el lugar, puede ofrecer servicios.`;if(p.type==='service')return`Punto útil para agua, lavado, vaciado u otros servicios. No se muestra necesariamente como lugar de pernocta.`;if(p.night)return`Lugar utilizado por viajeros para pasar la noche. No es necesariamente un área oficial: la utilidad de esta ficha es saber que existen experiencias de pernocta y qué condiciones o restricciones se conocen.`;return`Parking o parada útil para visitar la zona. No tenemos una experiencia de pernocta suficientemente clara como para marcarlo como lugar de noche.`}
function badges(p){const a=[typeText(p.type),p.price||'Precio desconocido'];if(p.night)a.push('🌙 Noche');if(p.sea)a.push('🌊 Mar cerca');if(p.status==='bad')a.push('⚠️ Precaución');return a}
function localRows(){try{return JSON.parse(localStorage.getItem('bc-family-camper-spots')||'[]')}catch{return[]}}
function all(){return rows.concat(localRows())}
function isVisible(p){const t=(p.name+' '+p.mun+' '+p.note).toLowerCase();if(query&&!t.includes(query))return false;if(filter==='night')return p.night&&p.status!=='bad';if(filter==='free')return /^gratis/i.test(p.price);if(filter==='sea')return p.sea;if(filter==='area')return p.type==='area';if(filter==='service')return p.type==='service';if(filter==='avoid')return p.status==='bad';return true}
function sorted(){return all().filter(isVisible).map(p=>({...p,d:user?dist(user.lat,user.lng,p.lat,p.lng):null})).sort((a,b)=>user?(a.d-b.d):(b.night-a.night)||a.name.localeCompare(b.name,'es'))}
function draftIcon(){return L.divIcon({className:'',html:'<div class="camper-marker service" style="font-size:18px">＋</div>',iconSize:[34,34],iconAnchor:[17,17]})}
function updateDraftCoords(lat,lng){$('#csLat').value=Number(lat).toFixed(6);$('#csLng').value=Number(lng).toFixed(6)}
function setDraftPoint(lat,lng){ensureMap();updateDraftCoords(lat,lng);if(!draftMarker){draftMarker=L.marker([lat,lng],{icon:draftIcon(),draggable:true,zIndexOffset:2000}).addTo(map).bindTooltip('Nuevo sitio · puedes mover el marcador',{permanent:false,direction:'top'});draftMarker.on('dragend',e=>{const p=e.target.getLatLng();updateDraftCoords(p.lat,p.lng)})}else draftMarker.setLatLng([lat,lng]);$('#camperAdd').classList.add('open');$('#camperSummary').textContent='📍 Punto seleccionado. Completa la ficha o mueve el marcador para ajustar la ubicación.';setTimeout(()=>$('#camperAdd').scrollIntoView({behavior:'smooth',block:'nearest'}),80)}
function startAddMode(){ensureMap();addMode=true;map.getContainer().style.cursor='crosshair';$('#camperShowAdd').textContent='📍 Toca el mapa';$('#camperAdd').classList.remove('open');$('#camperSummary').textContent='➕ Toca en el mapa exactamente donde está el sitio que quieres añadir.';map.getContainer().scrollIntoView({behavior:'smooth',block:'center'})}
function stopAddMode(removeDraft=true){addMode=false;if(map)map.getContainer().style.cursor='';$('#camperShowAdd').textContent='➕ Añadir sitio';if(removeDraft&&draftMarker&&map){map.removeLayer(draftMarker);draftMarker=null}}
function ensureMap(){if(map)return;map=L.map('camperMap').setView([39.66,2.98],9);const normal=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});normal.addTo(map);L.control.layers({'🗺️ Normal':normal,'🛰️ Satélite':satellite},null,{position:'topright',collapsed:true}).addTo(map);map.on('click',e=>{if(!addMode)return;setDraftPoint(e.latlng.lat,e.latlng.lng)});renderMarkers()}
function markerIcon(p){return L.divIcon({className:'',html:`<div class="camper-marker ${iconClass(p)}">${p.status==='bad'?'!':p.type==='service'?'🚰':p.type==='area'?'🚐':p.night?'🌙':'P'}</div>`,iconSize:[30,30],iconAnchor:[15,15]})}
function renderMarkers(){if(!map)return;for(const m of markers.values())map.removeLayer(m);markers.clear();for(const p of sorted()){const m=L.marker([p.lat,p.lng],{icon:markerIcon(p),title:p.name}).addTo(map);m.on('click',()=>{if(addMode)return;openSpot(p.id)});markers.set(p.id,m)}}
function openSpot(id){const p=all().find(x=>x.id===id);if(!p)return;const d=user?dist(user.lat,user.lng,p.lat,p.lng):null;const imgs=photos(p);$('#camperGallery').innerHTML=imgs.length?imgs.map((u,i)=>`<img loading="lazy" src="${u}" alt="Foto de referencia de ${esc(p.mun)}" onerror="this.remove()">`).join(''):`<div class="camper-photo-fallback">🚐🌙</div>`;
$('#camperDetail').innerHTML=`<h2>${esc(p.name)}</h2><div class="camper-detail-sub">${esc(p.mun)} · ${esc(typeText(p.type))}</div><div class="camper-status ${iconClass(p)}">${statusText(p)}</div>${d!=null?`<div class="camper-distance">📍 ${d.toFixed(1)} km desde ti</div>`:''}<div class="camper-badges">${badges(p).map(x=>`<span class="camper-badge">${esc(x)}</span>`).join('')}</div><div class="camper-section"><h3>Cómo es</h3><p>${esc(desc(p))}</p></div><div class="camper-section ${p.status==='bad'?'camper-warning bad':'camper-warning'}"><h3>Información práctica / restricciones</h3><p>${esc(p.note||'Sin observaciones adicionales. Comprueba la señalización al llegar.')}</p></div><div class="camper-section"><h3>Coordenadas</h3><p>${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}</p></div><div class="camper-detail-actions"><a class="btn primary" target="_blank" rel="noopener" href="${route(p)}">📍 Ir con Google Maps</a><a class="btn" target="_blank" rel="noopener" href="${pointMap(p)}">🗺️ Ver en Maps</a></div>${p.source?`<div class="camper-source">Referencia comunitaria/externa usada para localizar el punto: <a target="_blank" rel="noopener" href="${esc(p.source)}">abrir fuente ↗</a></div>`:''}<div class="camper-source">Las fotos, cuando aparecen, son imágenes de contexto de Wikimedia Commons y pueden representar la zona, no necesariamente la plaza exacta.</div>`;
$('#camperSheet').classList.add('open')}
function closeSpot(){$('#camperSheet').classList.remove('open')}
function renderList(){const items=sorted(),el=$('#camperList');el.innerHTML='';$('#camperSummary').textContent=user?`${items.length} puntos · ordenados por distancia desde tu ubicación`:`${items.length} puntos · activa GPS para ver la distancia desde ti`;
for(const p of items){const d=user?dist(user.lat,user.lng,p.lat,p.lng):null;const c=document.createElement('article');c.className='camper-card';c.innerHTML=`<div class="camper-card-head"><div><h3>${esc(p.name)}</h3><div class="camper-meta">${esc(p.mun)}${d!=null?` · ${d.toFixed(1)} km`:''}</div></div><div class="camper-price">${esc(p.price)}</div></div><div class="camper-status ${iconClass(p)}">${statusText(p)}</div><div class="actions"><button class="btn" data-open="${esc(p.id)}">Ver ficha</button><a class="btn primary" target="_blank" rel="noopener" href="${route(p)}">Google Maps</a></div>`;el.appendChild(c)}
$$('[data-open]').forEach(b=>b.onclick=()=>openSpot(b.dataset.open))}
function render(){ensureMap();renderMarkers();renderList()}
function setUser(lat,lng){user={lat,lng};ensureMap();if(!userMarker)userMarker=L.marker([lat,lng],{icon:L.divIcon({className:'',html:'<div class="camper-user-marker"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map).bindTooltip('Tu ubicación');else userMarker.setLatLng([lat,lng]);map.setView([lat,lng],11);render()}
function gps(){if(!navigator.geolocation)return alert('Este dispositivo no permite usar la ubicación.');navigator.geolocation.getCurrentPosition(p=>setUser(p.coords.latitude,p.coords.longitude),e=>alert(e.code===1?'Permiso de ubicación denegado.':'No se ha podido obtener tu ubicación.'),{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
function saveSpot(){const name=$('#csName').value.trim(),mun=$('#csMun').value.trim(),lat=Number($('#csLat').value),lng=Number($('#csLng').value);if(!name||!Number.isFinite(lat)||!Number.isFinite(lng)){alert('Indica nombre y selecciona la ubicación en el mapa.');return}const exp=$('#csExp').value,type=$('#csType').value,p={id:'family-'+Date.now(),name,mun:mun||'Mallorca',lat,lng,type,price:$('#csPrice').value,night:exp==='night',sea:$('#csSea').checked,status:exp==='bad'?'bad':'warn',note:$('#csNote').value.trim()||'Añadido por un miembro de la familia.',source:''};const a=localRows();a.push(p);localStorage.setItem('bc-family-camper-spots',JSON.stringify(a));$('#camperAdd').classList.remove('open');stopAddMode(true);render();openSpot(p.id)}
function shareSpot(){const text=`Nuevo punto CAMPER FAMILY\n${$('#csName').value}\n${$('#csMun').value}\n${$('#csLat').value}, ${$('#csLng').value}\n${$('#csNote').value}`;if(navigator.share)navigator.share({title:'Nuevo punto CAMPER',text}).catch(()=>{});else navigator.clipboard?.writeText(text)}
function initEvents(){document.querySelector('.tab[data-view="camper"]')?.addEventListener('click',()=>setTimeout(()=>{ensureMap();map.invalidateSize();render()},60));$('#camperGps').onclick=gps;$('#camperMallorca').onclick=()=>{ensureMap();map.setView([39.66,2.98],9)};$('#camperSearch').oninput=e=>{query=e.target.value.toLowerCase().trim();render()};$$('.camper-chip').forEach(b=>b.onclick=()=>{filter=b.dataset.f;$$('.camper-chip').forEach(x=>x.classList.toggle('on',x===b));render()});$('#camperSheetClose').onclick=closeSpot;$('#camperSheet').onclick=e=>{if(e.target===$('#camperSheet'))closeSpot()};$('#camperShowAdd').onclick=()=>{if(addMode){stopAddMode(true);$('#camperAdd').classList.remove('open');renderList()}else startAddMode()};$('#camperAddClose').onclick=()=>{$('#camperAdd').classList.remove('open');stopAddMode(true);renderList()};$('#camperUseGps').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>setDraftPoint(p.coords.latitude,p.coords.longitude));$('#camperSaveSpot').onclick=saveSpot;$('#camperShareSpot').onclick=shareSpot}
initEvents();window.BeachCamCamper={openSpot,render,count:()=>all().length};
})();