const cfg=window.BEACH_CAM_FIREBASE||{};
const setup=document.querySelector('#setupPanel'),login=document.querySelector('#loginPanel'),master=document.querySelector('#masterPanel'),msg=document.querySelector('#loginMsg'),count=document.querySelector('#deviceCount'),list=document.querySelector('#deviceList'),masterNav=document.querySelector('#masterNav');
let map=null,markers={},locations={},aliases={},familyKey='';
function configured(){return !!(cfg.enabled&&cfg.masterEmail&&cfg.firebaseConfig?.apiKey&&cfg.firebaseConfig?.databaseURL)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function age(ts){if(!ts)return'—';let s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return`hace ${s} s`;let m=Math.floor(s/60);if(m<60)return`hace ${m} min`;let h=Math.floor(m/60);if(h<24)return`hace ${h} h`;return`hace ${Math.floor(h/24)} d`}
function fullTime(ts){if(!ts)return'—';try{return new Date(ts).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'medium'})}catch{return new Date(ts).toLocaleString()}}
function google(lat,lng){return`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`}
function ensureMap(){if(map)return;map=L.map('masterMap').setView([39.65,2.95],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map)}
function displayName(uid,d){return aliases[uid]||d.label||`BCC ${uid.slice(-4).toUpperCase()}`}
function pointTime(d){return d.capturedAt||d.updatedAt||0}
function bccEntries(){return Object.entries(locations||{}).filter(([,d])=>d?.app==='bcc'&&Number.isFinite(d?.lat)&&Number.isFinite(d?.lng))}
function fitAll(){ensureMap();const pts=bccEntries().map(([,d])=>[d.lat,d.lng]);if(!pts.length){map.setView([39.65,2.95],9);return}if(pts.length===1){map.setView(pts[0],13);return}map.fitBounds(L.latLngBounds(pts).pad(.25),{maxZoom:14})}
function renderDevices(){ensureMap();let entries=bccEntries();entries.sort((a,b)=>pointTime(b[1])-pointTime(a[1]));count.textContent=`${entries.length} dispositivo${entries.length===1?'':'s'} BCC`;list.innerHTML='';let activeIds=new Set();for(const [uid,d] of entries){activeIds.add(uid);const name=displayName(uid,d),taken=pointTime(d);let stale=!taken||Date.now()-taken>5*60*1000;let status=d.online&&!stale?'Ubicación reciente':'ÚLTIMA UBICACIÓN GUARDADA';let cls=d.online&&!stale?'ok':'warn';let marker=markers[uid];if(!marker){marker=L.marker([d.lat,d.lng],{title:name}).addTo(map);markers[uid]=marker}else marker.setLatLng([d.lat,d.lng]);marker.bindTooltip(`${name} · ${age(taken)}`);let card=document.createElement('article');card.className='device';card.innerHTML=`<h3>${esc(name)}</h3><div class="status ${cls}">● ${status}</div><div class="meta"><strong>App:</strong> BEACH CAM CAMPER</div><div class="meta"><strong>Posición:</strong> ${age(taken)} · ${esc(fullTime(taken))}</div><div class="meta"><strong>Precisión GPS:</strong> ${d.accuracy?Math.round(d.accuracy)+' m':'—'}</div><div class="row"><button class="btn" data-center>Ver ubicación</button><a class="btn" target="_blank" rel="noopener" href="${google(d.lat,d.lng)}">Google Maps</a></div><div class="row"><button class="btn" data-rename>Renombrar</button><button class="btn" data-remove>Eliminar</button></div>`;list.appendChild(card);card.querySelector('[data-center]').onclick=()=>map.setView([d.lat,d.lng],16);card.querySelector('[data-rename]').onclick=async()=>{let n=prompt('Nombre que quieres ver en MASTER BCC:',name);if(n==null)return;n=n.trim().slice(0,40);if(!n)return;await firebase.database().ref(`aliases/${uid}`).set(n)};card.querySelector('[data-remove]').onclick=async()=>{if(!confirm(`¿Eliminar ${name} del MASTER BCC?`))return;await Promise.all([firebase.database().ref(`revoked/${uid}`).set(true),firebase.database().ref(`locations/${uid}`).remove(),firebase.database().ref(`aliases/${uid}`).remove()])}}
for(const [uid,m] of Object.entries(markers)){if(!activeIds.has(uid)){map.removeLayer(m);delete markers[uid]}}}
function invitationUrl(){if(!familyKey)return'';return `${location.origin}${location.pathname.replace(/master\.html$/,'install.html')}?join=${encodeURIComponent(familyKey)}`}
function renderInvite(){const url=invitationUrl(),input=document.querySelector('#inviteUrl'),qr=document.querySelector('#inviteQr');if(!url)return;input.value=url;qr.innerHTML='';new QRCode(qr,{text:url,width:210,height:210,correctLevel:QRCode.CorrectLevel.M});document.querySelector('#copyInvite').onclick=async()=>{await navigator.clipboard.writeText(url);document.querySelector('#inviteMsg').textContent='Enlace BCC copiado.'};document.querySelector('#shareInvite').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'BEACH CAM CAMPER',text:'Instala BEACH CAM CAMPER. La vinculación familiar es automática:',url})}catch{}}else{await navigator.clipboard.writeText(url);document.querySelector('#inviteMsg').textContent='Enlace BCC copiado para enviarlo.'}};document.querySelector('#downloadQr').onclick=()=>{const canvas=qr.querySelector('canvas'),img=qr.querySelector('img');let href=canvas?.toDataURL('image/png')||img?.src;if(!href)return;let a=document.createElement('a');a.href=href;a.download='BEACH-CAM-CAMPER-QR-FAMILIA.png';a.click()}}
async function prepareFamilyKey(){const snap=await firebase.database().ref('_private/familyKey').once('value');familyKey=snap.val()||'';if(!familyKey)throw new Error('No existe todavía la clave familiar. Entra una vez en el MASTER v13 para crearla.');renderInvite()}
function setupTabs(){masterNav.classList.remove('hidden');masterNav.querySelectorAll('[data-master-view]').forEach(btn=>btn.onclick=()=>{masterNav.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===btn));document.querySelectorAll('.master-view').forEach(v=>v.classList.remove('on'));document.querySelector(`#master-${btn.dataset.masterView}`).classList.add('on');if(btn.dataset.masterView==='devices'){setTimeout(()=>{map?.invalidateSize();fitAll()},50)}})}
async function loginMaster(){msg.textContent='Entrando…';msg.className='status';try{if(!firebase.apps.length)firebase.initializeApp(cfg.firebaseConfig);let email=document.querySelector('#email').value.trim(),pass=document.querySelector('#password').value;if(email.toLowerCase()!==String(cfg.masterEmail).toLowerCase())throw new Error('Este usuario no está autorizado.');await firebase.auth().signInWithEmailAndPassword(email,pass);login.classList.add('hidden');master.classList.remove('hidden');setupTabs();ensureMap();await prepareFamilyKey();firebase.database().ref('locations').on('value',s=>{locations=s.val()||{};renderDevices();fitAll()});firebase.database().ref('aliases').on('value',s=>{aliases=s.val()||{};renderDevices()});document.querySelector('#fitAll').onclick=fitAll;document.querySelector('#logoutMaster').onclick=async()=>{await firebase.auth().signOut();location.reload()};setInterval(renderDevices,60000)}catch(e){msg.textContent=e.message||'No se ha podido iniciar sesión.';msg.className='status err'}}
if(!configured()){setup.classList.remove('hidden')}else{login.classList.remove('hidden');document.querySelector('#email').value=cfg.masterEmail;document.querySelector('#loginBtn').onclick=loginMaster;document.querySelector('#password').addEventListener('keydown',e=>{if(e.key==='Enter')loginMaster()})}
